version: "3"
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /home/test/node_modules
      - ./:/home/test
    stdin_open: true
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /home/test/node_modules
      - ./:/home/test
    command: ["npm", "run", "test"]